### ISSUE TITLE
如何发送post type

### ISSUE THREAD

**Issue by zhangzhaorui** [ayunwSky/promalert-feishu-webhook#9]
老师您好，请教个问题，我的Alertmanager的tmpl是以下这种格式的：
{{ define "wechat.default.message" }}
{{- if gt (len .Alerts.Firing) 0 -}}
{{- range $index, $alert := .Alerts -}}
{{- if eq $index 0 }}
========= 异常报警 =========
告警状态：{{   .Status }}
告警级别：{{ .Labels.severity }}
告警类型：{{ $alert.Labels.alertname }}
故障主机: {{ $alert.Labels.instance }}
告警主题: {{ $alert.Annotations.summary }}
告警详情: {{ $alert.Annotations.message }}{{ $alert.Annotations.description}};
触发阀值：{{ .Annotations.value }}
故障时间: {{ $alert.StartsAt.Local }}
========= = end =  =========
{{- end }}
{{- end }}
{{- end }}
{{- if gt (len .Alerts.Resolved) 0 -}}
{{- range $index, $alert := .Alerts -}}
{{- if eq $index 0 }}
========= 异常恢复 =========
告警类型：{{ .Labels.alertname }}
告警状态：{{   .Status }}
告警主题: {{ $alert.Annotations.summary }}
告警详情: {{ $alert.Annotations.message }}{{ $alert.Annotations.description}};
故障时间: {{ $alert.StartsAt.Local }}
恢复时间: {{ $alert.EndsAt.Local }}
{{- if gt (len $alert.Labels.instance) 0 }}
实例信息: {{ $alert.Labels.instance }}
{{- end }}
========= = end =  =========
{{- end }}
{{- end }}
{{- end }}
{{- end }}

2, Alertmanager的报警条件我是这样配置的：

groups:
  - name: test-jvm-alerting
    rules:
    - alert: instance-down
      expr: up{instance="10.13.100.44:12345"} == 0
      for: 1m
      labels:
        severity: critical
        level: L0
      annotations:
        summary: "[test] Instance {{ $labels.instance }} 进程异常时间超过1min了"
        description: "[test] {{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minutes.监控图请查看：http://10.11.140.13:3000/d/2gbhhwH4z1111/new-trackingjian-kong?orgId=1&refresh=30s&var-instance=All"

3，问题描述：报错
[2023-03-23 11:28:08,799] INFO in main: {'receiver': 'prometheusalert-feishu', 'status': 'firing', 'alerts': [{'status': 'firing', 'labels': {'alertname': 'instance-down', 'instance': '10.13.100.44:12345', 'job': 'new-tracking', 'level': 'L0', 'severity': 'critical'}, 'annotations': {'description': '[test] 10.13.100.44:12345 of job new-tracking has been down for more than 1 minutes.监控图请查看：http://10.11.140.13:3000/d/2gbhhwH4z1111/new-trackingjian-kong?orgId=1&refresh=30s&var-instance=All', 'summary': '[test] Instance 10.13.100.44:12345 进程异常时间超过1min了'}, 'startsAt': '2023-03-23T03:17:15.114Z', 'endsAt': '0001-01-01T00:00:00Z', 'generatorURL': 'http://tc_140_13:9090/graph?g0.expr=up%7Binstance%3D%2210.13.100.44%3A12345%22%2Cjob%3D%22new-tracking%22%7D+%3D%3D+1&g0.tab=1', 'fingerprint': 'babc5238cb246961'}], 'groupLabels': {'alertname': 'instance-down', 'instance': '10.13.100.44:12345', 'job': 'new-tracking'}, 'commonLabels': {'alertname': 'instance-down', 'instance': '10.13.100.44:12345', 'job': 'new-tracking', 'level': 'L0', 'severity': 'critical'}, 'commonAnnotations': {'description': '[test]10.13.100.44:12345 of job new-tracking has been down for more than 1 minutes.监控图请查看：http://10.11.140.13:3000/d/2gbhhwH4z1111/new-trackingjian-kong?orgId=1&refresh=30s&var-instance=All', 'summary': '[test] Instance 10.13.100.44:12345 进程异常时间超过1min了'}, 'externalURL': 'http://tc_140_13:9093', 'version': '4', 'groupKey': '{}/{level=~"^(?:L0)$"}:{alertname="instance-down", instance="10.13.100.44:12345", job="new-tracking"}', 'truncatedAlerts': 0}
[2023-03-23 11:28:08,800] ERROR in app: Exception on /send [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/feishu-webhook/main.py", line 114, in send
    send_data = json.dumps(send_data)
                           ^^^^^^^^^
UnboundLocalError: cannot access local variable 'send_data' where it is not associated with a value
10.11.140.13 - - [23/Mar/2023 11:28:08] "POST /send HTTP/1.1" 500 -

4, 我的APP_FS_ALERT_TYPE: interactive 采用卡片模式

**Comment by ayunwSky** [comment]
interactive 采用卡片模式已经支持，辛苦再次尝试。
